[project]
name = "prodsec-challenge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Andrew Schmitt", email = "andrew@ajschmitt.io" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.141.1",
    "httpx==0.28.1",
    "pyjwt==2.13.0",
    "requests==2.34.2",
    "uvicorn==0.52.4",
]

[dependency-groups]
dev = [
    "ruff>=0.16.5",
]

[tool.bandit]
exclude_dirs = ["tests", ".venv"]
